### ISSUE TITLE
Upgrade guide for 3.8 is missing

### ISSUE THREAD

**Issue by joejulian** [gluster/glusterdocs#133]
There is no upgrade guide for 3.8

**Comment by humblec** [comment]
@joejulian ideally it should have been contributed by  3.8 release lead.  @pranithk or @aravindavk can you please check on this?

**Comment by humblec** [comment]
ah.. My bad. It would have assigned to @nixpanic

**Comment by nixpanic** [comment]
There should not be any special steps needed to upgrade from the latest 3.7.x to 3.8. If so, none of the developers informed me about it. The [release notes](https://github.com/gluster/glusterfs/blob/release-3.8/doc/release-notes/3.8.0.md) describe some of the changes and would have contained additional upgrade steps if known.

Depending on the distribution we might want to write some steps though... The packages in the CentOS Storage SIG provide a 3.7 or a 3.8 yum repository file. Upgrading from 3.7 to 3.8 requires uninstalling and installing the different centos-release-gluster packages. The [CentOS wiki](https://wiki.centos.org/SpecialInterestGroup/Storage/Gluster) would be the right place for that, I guess?

**Comment by joejulian** [comment]
If we're going to point users at downstream documentation for a 3.7 
(upstream) to 3.8 (downstream) upgrade process, we need to at least have 
a page that does that.

**Comment by nixpanic** [comment]
Do we have a page that describes updating steps? Even for minor releases like 3.7.13 to .14? I guess we could add a note there and point to the documentation for different distributions? I do not think Fedora has Gluster added to the release notes, but maybe we should consider that for the next version update?

**Comment by humblec** [comment]
@nixpanic as part of the release process, we normally provide an 'upgrade guide'. There is nothing wrong if we mention different upgrade process for different distros in the same repo. Also, maintaining upgrade guides in distros may not be the right solution as we only ship a particular version in that distro update. For ex: 3.6 in f21 , 3.7 in f22..etc.  I vote for a common guide as we did in the past for general use. Thats my view here.

**Comment by nixpanic** [comment]
There is no mentioning of "upgrade guides" in our current release process. We should add that if needed. I wasn't even aware we had them in the docs already. It is unfortunate that nobody mentioned this while the release of 3.8 was in progress.

Could someone add a page that says something like "upgrade from current 3.7 releases to 3.8 is done the same way as updates of minor releases"?

**Comment by humblec** [comment]
@nixpanic added in the new release process page.

**Comment by melbit-dannyw** [comment]
But does 3.8 allow a rolling upgrade like 3.7 and 3.5?  3.6 did not allow it.  It needs to be clarified as there is still no upgrade document provided on upgrading to 3.8.

**Comment by joejulian** [comment]
@melbit-dannyw 3.6 does allow rolling upgrades. There's only _rarely_ bugs that prevent that, and then it's usually between specific minor versions.

**Comment by humblec** [comment]
>
Could someone add a page that says something like "upgrade from current 3.7 releases to 3.8 is done the same way as updates of minor releases"?
>
@nixpanic now there is a mention about the upgrade guide in the release process http://gluster.readthedocs.io/en/latest/Contributors-Guide/GlusterFS-Release-process/ can you please place one for 3.8 ?

**Comment by humblec** [comment]
@nixpanic ping ? any update on this ?

**Comment by sankarshanmukhopadhyay** [comment]
3.8 has been a bit long in the tooth - what keeps this issue in 'Open' state?

**Comment by nixpanic** [comment]
This should have been closed when the upgrade guide got merged. I'm not a doc maintainer, but will close this now.
