### ISSUE TITLE
Possible workaround for search issues

### ISSUE THREAD

**Issue by amye** [gluster/glusterdocs#134]
https://github.com/rtfd/readthedocs.org/issues/1088 
## 

I'm not sure if we're using the same json that this issue references, but we could work on overriding the searchbox.html to replace this with something else. 

Assigning to @humblec so that he can tell me if I am crazy or if this could work.

**Comment by amye** [comment]
@humblec, am I crazy? Could we overwrite this?

**Comment by humblec** [comment]
@amye finding out :) . Give me some time. I will get back.

**Comment by humblec** [comment]
@amye at present we use the standard templates of mkdocs and RTD (https://github.com/gluster/glusterdocs/blob/master/mkdocs.yml) without any customization . Looking at the thread, it seems to me that customizing the search could help us. @prashanthpai what do u think ?

**Comment by amye** [comment]
Either a custom Google search or a more elaborate elasticsearch setup is where I am thinking, but that will require @mscherer's help.

**Comment by amye** [comment]
Alternatively, @prashanthpai - this seems to be a confirmed workaround. 
https://github.com/nodemcu/nodemcu-firmware/commit/7dd89dd15ef993c9740ba4d4361e6be8edd1284b

**Comment by helmo** [comment]
I'm seeing 404's when I click in the search results on http://gluster.readthedocs.io

Would that also be solved by this? e.g. searching for 'brick' gives [gluster - Brick Failure Detection](http://gluster.readthedocs.io/en/latest/Features/brick-failure-detection/?highlight=brick) as first result which returns a 404.

**Comment by nigelbabu** [comment]
Ugh, that file hasn't existed on the repo since 2015 :(

**Comment by prashanthpai** [comment]
This has been fixed to some extent by PR #255

**Comment by sankarshanmukhopadhyay** [comment]
If https://github.com/gluster/glusterdocs/pull/255 address some pertinent parts of this - can we either split this issue out and/or close the part which is done? Or, close this entire issue itself?

**Comment by nigelbabu** [comment]
Yeah, this is safe to close.
