### ISSUE TITLE
3.7 upgrade guide shows rolling upgrade instructions as "[TBD]"

### ISSUE THREAD

**Issue by joejulian** [gluster/glusterdocs#135]
Have we determined if there are rolling upgrade instructions yet?

https://github.com/gluster/glusterdocs/blob/master/Upgrade-Guide/Upgrade%20to%203.7.md

**Comment by humblec** [comment]
@joejulian above instructions should work. However I am not sure whether its been tested with latest versions of 3.7.

**Comment by joejulian** [comment]
Then the "TBD" should be removed if it's been tested. It's causing 
confusion.

**Comment by humblec** [comment]
@joejulian I am removing it . Thanks for pointing it out.

**Comment by humblec** [comment]
@joejulian  Done. https://github.com/gluster/glusterdocs/blob/master/Upgrade-Guide/Upgrade%20to%203.7.md
Closing this issue for now.
