### ISSUE TITLE
Provide a similar look-and-feel for the docs as use used on gluster.org

### ISSUE THREAD

**Issue by nixpanic** [gluster/glusterdocs#140]
The docs do not look similar to the style on gluster.org at all. It would make the docs look more official when the style matches the main website.

**Comment by humblec** [comment]
@nixpanic you may put some more pointers on this .  @amye is it something you can help with ?

**Comment by kshlm** [comment]
Sorry for going OT. But blog.gluster.org also doesn't follow the style of the main site. Where would I report bugs for that? Bugzilla under 'project-infra'?

**Comment by amye** [comment]
@kshlm: blog.gluster.org is an entirely separate property. 
@nixpanic: This is a current limitation of the RTD platform, cannot be resolved with current tooling.

**Comment by nixpanic** [comment]
Don't we use mkdocs for the generation? That should support custom themes like documented on http://mkdocs.readthedocs.io/en/latest/user-guide/custom-themes/

If it can not be resolved with the current tooling, we should probably keep this open and fix it when the tooling improves. Pretty unexpected that there are still platforms that do not allow changing the displayed style.

**Comment by nixpanic** [comment]
Where can we request and track the blog.gluster.org theme changes?

**Comment by sankarshanmukhopadhyay** [comment]
@amye - is this done and can this be closed?

**Comment by nixpanic** [comment]
https://docs.gluster.org still does not look integrated with the rest of https://gluster.org - I have hopes that someone will provide a matching RTD theme for it.

**Comment by sankarshanmukhopadhyay** [comment]
@nixpanic from how I look at it - this isn't the item which is likely to happen soon. So, unless we get contributions which make this happen - it might be worthwhile to close the issue.

**Comment by amye** [comment]
This refers to back when we had a cloud-based Gluster background, not the current white-based background. New issue with link to contribution of RTD theme can be opened.
