### ISSUE TITLE
Merge (old) Jenkins pages into the OPS Guide

### ISSUE THREAD

**Issue by nixpanic** [gluster/glusterdocs#142]
There are ate least two older Jenkins pages:
- http://gluster.readthedocs.io/en/latest/Developer-guide/Jenkins-Infrastructure/
- http://gluster.readthedocs.io/en/latest/Developer-guide/Jenkins-Manual-Setup/

The new [OPS Guide](http://gluster.readthedocs.io/en/latest/Ops-Guide/Overview/) should probably have those pages instead. Or maybe the old Jenkins descriptions can be deprecated?

**Comment by mscherer** [comment]
We can for sure drop the 2nd file, and I guess the first is of dubious historical utility. However, not all servers are documented yet on the ops docs, so we could just add a minimal list somewhere and then remove the file ? (also, "Jenkins infra", when there is slightly more than jenkins is misleading)

**Comment by humblec** [comment]
@mscherer @nixpanic Is there a PR on this ?

**Comment by sankarshanmukhopadhyay** [comment]
@nigelbabu @mscherer - is this issue still relevant?

**Comment by nigelbabu** [comment]
Nope.
