### ISSUE TITLE
Gluster Setup for Anything but CentOS/RHEL Incorrect

### ISSUE THREAD

**Issue by Illydth** [gluster/glusterdocs#179]
With the migration of Gluster into the CentOS Storage SIG, there are no longer "public" packages for "other" RHEL Variants other than RHEL or CentOS...even the instructions for installing on RHEL are unclear as it requires a CentOS Release Package to Install.

Meaning, there's no clear installation method on pretty much any system but Cent at this point.  This locks out:
* ROSA Enterprise Linux Server
* Scientific Linux
* ClearOS
* Oracle Linux

Just to name a few.  

At this point to install on Oracle Linux, I had to track down the centos-release package, track down the centos-release-storage-common package, track down the centos-release-gluster38 package, track down what that package contains...just to get to the REPO file.  From there the baseURL in that REPO file is broken requiring me to manually go out to Cent's archives and browse for the URL.
* baseurl=http://mirror.centos.org/centos/$releasever/storage/$basearch/gluster-3.8/ (WRONG)
* baseurl=http://mirror.centos.org/centos-7/7/storage/x86_64/gluster-3.8/ (RIGHT)

Hand waving your documentation with "Ey, if it's a RHEL clone just go do what Cent tells you" as your installation instructions is just ridiculously short sighted.  Especially when Cent moves the repository into what is apparently a "CentOS only format".  

The repo is NOT an "open" repository in the sense that you can install the repo file via a downloadable repo package from the Web, unlike stand alone repositories like Docker and EPEL.  It is VERY MUCH a CentOS only repository with no "easy" installation method unless you are using CentOS (only) as your base OS.  RPM centos-release-gluster38 relies upon centos-release-storage-common which itself relies upon centos-release to install.  Centos-release will conflict with ANY release package on ANY OS Distribution except CentOS, meaning there is no RPM based way to get ahold of the repo file to install gluster.

If Gluster is intending to be adopted by a broader enterprise community than "RHEL Users" only, this kind of hand waving documentation and tight integration with specific OS Distributions needs to be strongly looked at and backed out.

The LEAST you guys could do would be to provide the proper REPO spec and a location to obtain the GPG Key (had to track that down myself also) directly in the documentation instead of assuming every business organization in the world is using CentOS.

**Comment by amye** [comment]
Two different things in here: 

1) I very much appreciate you offering your take on where our Gluster documentation can be improved. As an open source project, we welcome input on where our direction could be.  

2) That being said, constructive points are also helpful, so thank you for the Oracle Install pointers. We'll review this and work with CentOS to correct their archives. 

Anything else that you notice on first review?
Thanks!
-- amye
