### ISSUE TITLE
needed more pacakge while installing gluster on fedora 

### ISSUE THREAD

**Issue by aj07** [gluster/glusterdocs#192]
While installing first time gluster on fedora, one package seems to be missed.
Error: `g++error:/usr/lib/rpm/redhat/redhat-hardened` 

It can be solved by running following [cmd..](http://stackoverflow.com/questions/34624428/g-error-usr-lib-rpm-redhat-redhat-hardened-cc1-no-that-file-and-directory)
`sudo dnf install redhat-rpm-config`

There is need to update page[https://gluster.readthedocs.io/en/latest/Developer-guide/Building-GlusterFS/](https://gluster.readthedocs.io/en/latest/Developer-guide/Building-GlusterFS/)

**Comment by humblec** [comment]
@aj07 Thanks..  Please send a PR.

**Comment by aj07** [comment]
PR #196

**Comment by nvtkaszpir** [comment]
This should be marked as closed becuase the PR was merged.
