### ISSUE TITLE
"About op-version" section in the "Upgrading GlusterFS" chapter needs updates for 3.10

### ISSUE THREAD

**Issue by ShyamsundarR** [gluster/glusterdocs#204]
In 3.10 we introduced the option to fetch maximum possible op-version that the cluster can be bumped to. This needs to be updated in this section of the guide.
Option: gluster volume get all cluster.max-op-version
Guide location: https://gluster.readthedocs.io/en/latest/Upgrade-Guide/op_version/

Further, checking client op-version was also supported, from my understanding we should also add that to this part of the guide to state that, a user can check the client op-version as well before making the decision to upgrade/update the op-version of the cluster.

It would be nice to have a PR for this by Fri. 24th, 2017 before we announce 3.10.0 release.

**Comment by samikshan** [comment]
PR up for review here: https://github.com/gluster/glusterdocs/pull/205
