### ISSUE TITLE
Update release-notes section with release-3.10 notes as well

### ISSUE THREAD

**Issue by ShyamsundarR** [gluster/glusterdocs#206]
Filing this issue in advance of 3.10 release, so that once the release announcements are made, the release notes from [1] can be posted on the doc site as well.

[1] Link will work once 3.10.0 is tagged: https://github.com/gluster/glusterfs/blob/v3.10.0/doc/release-notes/3.10.0.md

**Comment by humblec** [comment]
@ShyamsundarR please send a PR which add the release notes in https://github.com/gluster/glusterdocs/tree/master/release-notes . We can merge it and keep for the release announcement.
