### ISSUE TITLE
op-version edit to the document needs 3.10 addition

### ISSUE THREAD

**Issue by ShyamsundarR** [gluster/glusterdocs#209]
http://gluster.readthedocs.io/en/latest/Upgrade-Guide/op_version/ does not say that the command to get the max op-version is supported only from 3.10 onward (I think we need that there, so that users with older versions do not attempt the same and file bugs :) ).

@samikshan can you take care of this?

**Comment by samikshan** [comment]
PR for review: https://github.com/gluster/glusterdocs/pull/211

**Comment by prashanthpai** [comment]
As @samikshan mentioned, this has been addressed in #211
