### ISSUE TITLE
Gluster needs more developer specific documentation

### ISSUE THREAD

**Issue by nbalacha** [gluster/glusterdocs#225]
glusterdocs needs to be updated with more information on gluster internals for developers interested in working on the project.

**Comment by humblec** [comment]
@nbalacha totally agree. All the developers has to contribute to achieve this goal. May be we have to come up with a mandatory process to improve the developer documentation. Any thoughts or ideas for the same ?

**Comment by prashanthpai** [comment]
@nbalacha @humblec All developer docs [currently resides in the glusterfs repo](https://github.com/gluster/glusterfs/tree/master/doc/developer-guide) and should continue to do so. This repo is only for admins and users of GlusterFS.

**Comment by nigelbabu** [comment]
@prashanthpai Does that mean the contributor guide doesn't have a place?

**Comment by prashanthpai** [comment]
@nigelbabu Not all contributors are developers. Contributions can come in many ways - documentation, bug reports, website maintenance etc. The [contributors guide](https://github.com/gluster/glusterdocs/blob/master/Contributors-Guide/Index.md) currently resides in this repo, which is the right place.

Developers who intend to review/send code patches to GlusterFS code repo (or hack privately) will be looking for documentation on internals (data structures, implementation details) of GlusterFS. This should reside in glusterfs repo as it is done today.

**Comment by humblec** [comment]
@prashanthpai @nbalacha yes, its in different source. However I thought @nbalacha's request here is to improve the same.
