### ISSUE TITLE
Wrong key location in Debian install instructions

### ISSUE THREAD

**Issue by jarrpa** [gluster/glusterdocs#302]
The docs (here)[https://github.com/gluster/glusterdocs/blob/master/Install-Guide/Install.md] say that you should at the following GPG key:
```
http://download.gluster.org/pub/gluster/glusterfs/LATEST/rsa.pub
```
Unfortunately, there's no such key file there. `glusterfs/LATEST` appears to just be a link to `glusterfs/3.12/LATEST`, but the key that you need to use is located at `glusterfs/3.12/rsa.pub`.

Either the instructions should be updated or some sort of link or duplicate of the required key should be maintained.

**Comment by prashanthpai** [comment]
PR #305 addresses this.
