### ISSUE TITLE
Rephrase this repo's description

### ISSUE THREAD

**Issue by mykaul** [gluster/glusterdocs#372]
Currently, it says:
'This repo had it's git history re-written on 19 May 2016. Please create a fresh fork or clone if you have an older local clone.'

Surely we can improve.

**Comment by prashanthpai** [comment]
The notice/announcement should stay, but may be in `README.md` instead and not description.

@nixpanic I don't seem to have permission to edit repo description. I remember you having them.

**Comment by nixpanic** [comment]
@prashanthpai yes, I can change it. Just let me know what the text should be.

**Comment by prashanthpai** [comment]
@nixpanic 

`This repo contains the source of official Gluster documentation rendered at http://docs.gluster.org/`

Feel free to improve/change it as you see fit.

**Comment by nixpanic** [comment]
The description has now been updated.
