### ISSUE TITLE
Red Hat 7 Installation

### ISSUE THREAD

**Issue by daurrutia** [gluster/glusterdocs#395]
> For Red Hat/CentOS
> RPMs for CentOS and other RHEL clones are available from the CentOS Storage SIG mirrors.

Is this still valid? Encountering difficulties attempting to find glusterfs-server and glusterfs-client for RHEL 7.x.

**Comment by sankarshanmukhopadhyay** [comment]
@daurrutia  I have a clarifying question - are you looking for RHEL binaries (which should be available from the content delivery networks for RHEL) or, binaries for CentOS etc?

**Comment by daurrutia** [comment]
Thanks for the quick reply @sankarshanmukhopadhyay.

I guess I'm looking for the RHEL binaries. The gluster docs simply point one to the CentOS Storage SIG.

I'm trying to figure out what is the "right" way to install glusterfs on RHEL 7.

**Comment by sankarshanmukhopadhyay** [comment]
Red Hat packages, ships and supports the Red Hat Gluster Storage product. More detail about documentation and packages are at https://access.redhat.com/products/red-hat-storage.

The existing documents which point to the CentOS Storage SIG do so if you would like to use packages built for CentOS and functionally validated by members of the SIG

**Comment by daurrutia** [comment]
Ok, so then I am looking to utilize the CentOS packages.

The issue I am running into maybe due to my limited knowledge of with yum repos. 

I have added the CentOS repos to my RHEL instance, however, when attempting to install centos-release-gluster41, I run into centos-release dependency transaction check errors, and gluster does not install.

[gfs-transactionerror.txt](https://github.com/gluster/glusterdocs/files/2249962/gfs-transactionerror.txt)

**Comment by daurrutia** [comment]
Was able to workaround by copying package and dependencies from CentOS 7 to RHEL 7.

Thanks @nixpanic . Will try #1 next.
