### ISSUE TITLE
Order of pages in release-notes and upgrade guide is lexical order

### ISSUE THREAD

**Issue by ShyamsundarR** [gluster/glusterdocs#411]
Prior to the move to latest mkdocs, the sections in release-notes and Upgrade-guide were following the order given in the mkdocs.yml file (or at least consistent with it).

Post the move (which is what I can determine, could be the wrong RCA here), it is in lexical order, and that messes up the view, and order of releases.

I am unsure how to correct this, posting the issue for attention.

Screen shot showing the current lexical order of strings:
![gluster-docs-lexical-order](https://user-images.githubusercontent.com/5372237/44480239-c2a3c380-a610-11e8-85cf-b858a2b018e0.png)

**Comment by nigelbabu** [comment]
This happened to the entire TOC. I discovered today that RTD does not look at the requirements.txt until we tell it to look there. While I was there, I got RTD to use python3 along with the latest mkdocs. This is now fixed with https://github.com/gluster/glusterdocs/pull/413
