### ISSUE TITLE
Reduce clutter in sidebar

### ISSUE THREAD

**Issue by ShyamsundarR** [gluster/glusterdocs#428]
I wanted to see how to reduce clutter w.r.t Upgrade guides and release notes in the side bar.

I was toying with the idea of adding a sidebar topic like "Older upgrade guides" and "Older release notes" and then linking the respective md files from that page. Thus the side bar has reduced elements in it.

As I understand if mkdocs.yml does not have the md file listed it is not built. Chasing this I found this issue in the mkdocs repository to be relevant: https://github.com/mkdocs/mkdocs/issues issue numbered 699 (do not want to generate a reference there).

How do we pull this off in glusterdocs?

**Comment by nigelbabu** [comment]
We have a test that runs with strict on so that we don't accidentally have a page that is published but not in the menu. So that one is a no go from the start.

**Comment by sankarshanmukhopadhyay** [comment]
I'm not sure where we left with this. @ShyamsundarR @nigelbabu - should this be closed?

**Comment by ShyamsundarR** [comment]
I do not have any alternatives to provide here, so if we cannot reduce it, we need to live with it I guess.
