### ISSUE TITLE
Gluster 5 release notes documentation link broken

### ISSUE THREAD

**Issue by sammcj** [gluster/glusterdocs#456]
Source page: https://www.gluster.org/announcing-gluster-5/

Link: https://docs.gluster.org/en/latest/release-notes/5

Result: Read the docs gives 'Maze found - Sorry this page does not exist yet"

Suggested fix: Update the link to https://docs.gluster.org/en/latest/release-notes/5.0/

**Comment by sammcj** [comment]
Note: I'd submit a MR for this myself but I can't see that announcing-gluster-5 page in the source repo?

**Comment by amarts** [comment]
@ShyamsundarR @amye

**Comment by ShyamsundarR** [comment]
Website link fixed.
