### ISSUE TITLE
Automatically Mounting Volumes Server down

### ISSUE THREAD

**Issue by sunyuanchao** [gluster/glusterdocs#491]
For example:
server1:/test-volume /mnt/glusterfs glusterfs defaults,_netdev 0 0

in this example, if server1 down, this mont directory how to do

**Comment by joejulian** [comment]
See https://github.com/gluster/glusterdocs/blob/master/docs/Administrator%20Guide/Setting%20Up%20Clients.md#manually-mounting-volumes

for support, please use the [mailing list](https://lists.gluster.org/mailman/listinfo/gluster-users)
