### ISSUE TITLE
Better documentation for new user to start

### ISSUE THREAD

**Issue by stopsopa** [gluster/glusterdocs#524]
Is this project dying or what? maintenance of the documentation doesn't seem to be very active.

for example https://gluster.readthedocs.io/en/latest/Administrator%20Guide/Setting%20Up%20Clients/
says that i need to install version glusterfs-3.8.5-1.x86_64 where it looks like newest version is at least glusterfs-7.1-1.el7.x86_64.rpm

and on the installation process I've ended up with errors like this:

![image](https://user-images.githubusercontent.com/3743506/72983699-d214d680-3dd9-11ea-88bf-315ff834890b.png)

How I as a new user supposed to know what to finally make it work if not from documentation?
Please don't waste users time and upgrade documentation and It would be nice if from time to time somebody would go through the installation process to make sure that everything works.

**Comment by sankarshanmukhopadhyay** [comment]
> Is this project dying or what? maintenance of the documentation doesn't seem to be very active.
> 
> for example https://gluster.readthedocs.io/en/latest/Administrator%20Guide/Setting%20Up%20Clients/
> says that i need to install version glusterfs-3.8.5-1.x86_64 where it looks like newest version is at least glusterfs-7.1-1.el7.x86_64.rpm

I apologize about this. We'll need to modify the segment where the installation package NVR is mentioned to indicate using the latest package sets from the download URL

[snip]

> Please don't waste users time and upgrade documentation and It would be nice if from time to time somebody would go through the installation process to make sure that everything works.

I agree. Thank you for exhorting us to do better for our users.

**Comment by stopsopa** [comment]
@sankarshanmukhopadhyay thank you for you swift reaction, but adding note to documentation didn't made situation any better, I still don't know how to mount it on other machine.

Really sorry for ranting but I've wasted half of my day and I didn't achieved anything except building cluster that I can't use at all in simplest scenario, not mentioning even integrating it with Kubernetes which is my final goal.

**Comment by sankarshanmukhopadhyay** [comment]
Ok. Let me walk back and understand if we have all the issues understood.

The first one was that the documentation did not explicitly mention about using the latest packages. Because of this error, your deployment has been broken. Additionally, you are facing issues related to mount points.

Are these the issues which are at present impacting the deployment? Is this a test instance or, a staging/non-production instance? I ask this to check if we can start from the beginning with the correct set of packages and follow the sequence of steps required.

**Comment by joejulian** [comment]
This appears to have been abandoned. Please re-open and respond to comments if it's still a valid documentation issue.
