### ISSUE TITLE
Removing the page about compiling binaries from source

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [gluster/glusterdocs#536]
"[How to compile GlusterFS RPMs from git source, for RHEL/CentOS, and Fedora](https://docs.gluster.org/en/latest/Install-Guide/compiling-rpms/)" has not aged well and is presently quite unmaintained. If this is not something a large number of our users do, I'd propose to remove this page from the listing/view.

@harigowtham @amarts - feedback requested on this proposal

**Comment by aravindavk** [comment]
I think this can be moved to "Developers" section

**Comment by harigowtham** [comment]
Yes, This looks outdated. We do have users who look for a particular fix in urgency. If its not due for it to be packaged we ask them to build it themselves or wait. Not sure how many of them have actually used this guide to build it themselves. But having such a thing, gives us the freedom to ask them to build it themselves without waiting/relying on us.

**Comment by sankarshanmukhopadhyay** [comment]
If this is only for a specific set of knowledgeable users then we can consider moving it to the Developers section

**Comment by harigowtham** [comment]
+1 to moving to Developers section
