### ISSUE TITLE
Add docs for gluster volume options

### ISSUE THREAD

**Issue by Sheetalpamecha** [gluster/glusterdocs#617]
Create a tabular format for all options available and their usage

**Comment by Sheetalpamecha** [comment]
Patch posted https://github.com/gluster/glusterdocs/pull/624/

**Comment by amarts** [comment]
were there only 3 options which were deprecated?

**Comment by Sheetalpamecha** [comment]
Yes from the documented ones only these three. But there are plenty of them have been added. Will work on them xlator by xlator
