### ISSUE TITLE
Expanding gluster volume

### ISSUE THREAD

**Issue by kalkir** [gluster/glusterdocs#629]
Currently we have created dispersed gluster volume with 3 bricks and using 1 redundancy, we would like to expand 4 more bricks. 
we are going to use redundancy count of 3, I could see the option 'gluster volume add-brick' but what would be the count of redundancy and disperse option.
Please confirm. 
eg: gluster volume add-brick server4:/brick1 serve5:/brick1 server6:/brick1 server7:/brick1 disperse 7 redundancy 3 ?

**Comment by kalkir** [comment]
Any update on this?
thanks

**Comment by balakreddy** [comment]
@kalkir From the existing disperse volume get gluster volume info, there you will find `Number of Bricks: 1 x (2 + 1) = 3`
You can only add bricks as multiple of the subvol brick count(Here subvol count is 2+1 = 3). If you try to add 4 bricks it will fail. No parameter like disperse 7 and redundancy 3 is needed while performing add-brick.

Volume add-brick fails as below when you add 4 bricks as below
`volume add-brick: failed: Incorrect number of bricks supplied 4 with count 3`

Hope this helps.

**Comment by balakreddy** [comment]
@kalkir Disperse count won't change, where as the volume will become distributed disperse.

Volume output after performing the add-brick. 
```
Volume Name: testvol
Type: Distributed-Disperse
Volume ID: bb41c258-0606-4838-ab85-6c15af42f456
Status: Created
Snapshot Count: 0
Number of Bricks: 2 x (2 + 1) = 6
Transport-type: tcp
Bricks:
Brick1: 192.168.0.11:/brick1/b1
Brick2: 192.168.0.12:/brick1/b2
Brick3: 192.168.0.13:/brick1/b3
Brick4: 192.168.0.11:/brick2/b4
Brick5: 192.168.0.12:/brick2/b5
Brick6: 192.168.0.13:/brick2/b6
Options Reconfigured:
transport.address-family: inet
storage.fips-mode-rchecksum: on
nfs.disable: on

```

Earlier when you have disperse volume  `1 x (2 + 1) = 3`, For eg  if you write 100 it will be stored in the 3 bricks.
After add-brick, If you write 100 files, now these 100 files will be distributed to two subvols.

**Comment by kalkir** [comment]
Thank you for your update, so in this case failure of 2 nodes won't affect the volume right?

**Comment by simonsben** [comment]
I think that depends on which nodes fail. Logically the volume spans all six, but I think the new drives just act as an extension to the first three. So since it would be a 2 x (2 + 1), you could loose one drive from each of the *sets of three* and be fine. But I think if you lost two from the same *sub-group* then you'd lose the info from those three drives

**Comment by kalkir** [comment]
Got it, Thanks for the clarification.
