### ISSUE TITLE
Removal of force option in the snapshot create feature in the documentation.

### ISSUE THREAD

**Issue by nishith-vihar** [gluster/glusterdocs#660]
As the force option is redundant and the snapshot create feature requires all the bricks to be online for creating a snapshot feature the force option should be removed and the quorum description should be removed.

**Comment by kshithijiyer** [comment]
Force option isn't removed from snapshot this issue is invalid https://github.com/gluster/glusterfs/blob/devel/cli/src/cli-cmd-snapshot.c#L73.
