### ISSUE TITLE
Adding new bricks to disperse volume.

### ISSUE THREAD

**Issue by kalkir** [gluster/glusterdocs#684]
I am trying to add 3 new bricks to the existing gluster volume, but the operation is timing out and i am seeing lock on all nodes. I had to remove the bricks for normal operation. Is there any standard procedure to add  bricks to an live volume? do I need to unmount client mounts before adding additional brick? I have tried following command. 

gluster volume add-brick gluster-vol 10.20.0.1:/bricks/gluster-vol/brick1/brick 10.20.0.2:/bricks/gluster-vol/brick1/brick 10.20.0.3:/bricks/gluster-vol/brick1/brick force
I saw following errors in glusterd logs

The message "E [MSGID: 106118] [glusterd-op-sm.c:4094:glusterd_op_ac_lock] 0-management: Unable to acquire lock for gluster-vol" repeated 3 times between [2021-05-25 05:08:44.133592 +0000] and [2021-05-25 05:09:35.687228 +0000]
The message "E [MSGID: 106376] [glusterd-op-sm.c:8042:glusterd_op_sm] 0-management: handler returned: -1" repeated 3 times between [2021-05-25 05:08:44.133611 +0000] and [2021-05-25 05:09:35.687247 +0000]
The message "W [MSGID: 106065] [glusterd-mgmt-handler.c:842:glusterd_handle_post_validate_fn] 0-management: Failed to unserialize dict []" repeated 2 times between [2021-05-25 05:08:50.383220 +0000] and [2021-05-25 05:09:35.688908 +000

please note that we have currently 3 bricks of 1.5 T, we are trying to add 3 more extra brick of size 1 T each.

**Comment by kalkir** [comment]
Can I get an update?

**Comment by karthik-us** [comment]
Hi @kalkir, This repository is for gluster documentation and for issues related to working of gluster, I would suggest raising one in https://github.com/gluster/glusterfs/issues, if not done already.

**Comment by kalkir** [comment]
Thanks, raised one issue.
