### ISSUE TITLE
Issue with command to enable NUFA

### ISSUE THREAD

**Issue by edwardchenchen** [gluster/glusterdocs#685]
https://github.com/gluster/glusterdocs/blob/main/docs/Administrator-Guide/Managing-Volumes.md
Line 706 
`gluster volume set <VOLNAME> cluster.nufa enable on`

I found the above command does not work, but when I tried with only enable or on.
It worked

![image](https://user-images.githubusercontent.com/6397192/120070813-a8f00e80-c0cf-11eb-99df-26736a059240.png)
![image](https://user-images.githubusercontent.com/6397192/120070825-b4dbd080-c0cf-11eb-9719-4069b25b8c4d.png)

My question is,
is both `enable `and `on `valid?

**Comment by nik-redhat** [comment]
Hi @edwardchenchen this seems to be a typo in the docs.
Yes, you can use `enable` or `on` to set the options requiring a boolean value.
