### ISSUE TITLE
Debian repositories are empty

### ISSUE THREAD

**Issue by jsschmid** [gluster/glusterdocs#705]
A

  sudo apt update

gives me a 

  Ign:10 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/10/amd64/apt buster InRelease                                                                                    
  Fehl:11 https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/10/amd64/apt buster Release                                                                                     
    404  Not Found [IP: 8.43.85.185 443]

So it seems that
  https://download.gluster.org/pub/gluster/glusterfs/LATEST/Debian/10/amd64/apt/dists/buster/main/binary-amd64/
is empty.

**Comment by Sheetalpamecha** [comment]
Hey @jsschmid, 
I checked and it seemed link was pointing to wrong directory and thus it was empty. 
Now it should work fine
