### ISSUE TITLE
Puzzling "when using hostnames" note in Quick Start

### ISSUE THREAD

**Issue by romanrm** [gluster/glusterdocs#706]
https://docs.gluster.org/en/latest/Quick-Start-Guide/Quickstart/

"Note: When using hostnames, the first server needs to be probed from one other server to set its hostname."

Sorry, what? For someone reading this as the first thing they read about GlusterFS, this bit sounds really puzzling as to what do you mean exactly. "The first server", i.e. server1 from the context? Or probe only server2 (= the first of the two listed immediately above), but not server3? And what is the purpose, to "set" its hostname, set in what sense? Up until now hostnames were "set" using OS means such as "hostname (1)"... Etc.

Please do not think it is sufficient to explain the above to *me* in this ticket, my suggestion is to expand or rephrase this "Note" in the doc.

**Comment by Shwetha-Acharya** [comment]
@nik-redhat

**Comment by nik-redhat** [comment]
Hi @romanrm , it is kind of insufficient, I agree. So, let me help you out with an example below.

The note tries to say is that we can use other names for the peers that we are using in our cluster
That is suppose you have a cluster `1.1.1.1`, `1.1.1.2`, `1.1.1.3`
And you peer probe like `gluster peer probe 1.1.1.2` from node `1.1.1.1`
Then, when you do a gluster peer status on `1.1.1.1` it will show the hostname of other nodes as `1.1.1.2` itself, but the output of gluster peer status in `1.1.1.2` might not shown the IP Address of the other nodes but instead show `server1` or the hostname which is set to be recognized by other ip's.
In such case, you can add another name for `server1` by peer probing from `1.1.1.2` using the ip-address directly i.e, `gluster peer probe 1.1.1.1` and the output of gluster peer status will show both the names of the other nodes using which once can reference.
Hopefully, this helps in understanding the note.
